#!/usr/bin/env python3
"""
1-async_comprehension

this module contains a coroutine called
async_comprehension that takes no arguments
and return a list of 10 randon numbers
by using asynchronous comprehension.
"""
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    This function use asynchronous comprehension for collect
    10 numbers generated by async_generator function
    """
    list_of_numbers = [number async for number in async_generator()]
    return list_of_numbers
